import type { Locale } from "@/lib/i18n/config";

export const persistedLessonCopy = {
  th: {
    metadataTitle: "ฝึกตรวจสอบแหล่งข้อมูลแบบบันทึกความคืบหน้า | Rise Pals",
    metadataDescription: "พื้นที่ฝึกสังเคราะห์ที่บันทึกคำตอบและผลตามเกณฑ์บนเซิร์ฟเวอร์",
    learningEyebrow: "พื้นที่เรียนรู้สังเคราะห์",
    learningHeading: "ความคืบหน้าการเรียนรู้",
    learningIntroduction: "หน้านี้แสดงเฉพาะกิจกรรมตัวอย่างที่บันทึกด้วยบัญชีและความยินยอมปัจจุบัน",
    lessonLink: "เปิดบทเรียนและแบบฝึกที่บันทึกความคืบหน้า",
    notStarted: "ยังไม่ได้เริ่ม",
    inProgress: "กำลังฝึก",
    needsRetry: "ลองปรับคำตอบอีกครั้ง",
    demonstrated: "แสดงพฤติกรรมตามเกณฑ์ครบแล้ว",
    boundaryHeading: "ขอบเขตอัลฟาสังเคราะห์",
    boundaries: [
      "ระบบเก็บรหัสตัวเลือกและความคืบหน้าสำหรับบัญชีที่ลงชื่อเข้าใช้ แต่ไม่คัดลอกอีเมลมาไว้ในบันทึกการเรียนรู้",
      "ระบบไม่เก็บข้อความอิสระหรือไฟล์ และพื้นที่ส่งหลักฐานยังไม่พร้อมใช้งาน",
      "นี่ไม่ใช่หลักฐานว่าบทเรียนผ่านการตรวจสอบประสิทธิผลกับผู้ใช้จริง",
      "ยังไม่มีการบันทึก XP การส่งหลักฐาน หรือคำแนะนำเฉพาะบุคคล",
      "การดูหน้าเพียงอย่างเดียวไม่เขียนข้อมูล ความคืบหน้าเกิดจากคำสั่งที่ชัดเจนเท่านั้น",
    ],
    consentHeading: "ต้องให้ความยินยอมข้อมูลบริการเวอร์ชันปัจจุบัน",
    consentBody: "ไปที่การเริ่มต้นใช้งานเพื่อทบทวนและให้ความยินยอมก่อนบันทึกความคืบหน้า",
    signInHeading: "ต้องลงชื่อเข้าใช้",
    unavailableHeading: "ยังเปิดพื้นที่เรียนรู้ไม่ได้",
    startLabel: "เริ่มและบันทึกความคืบหน้า",
    saveLabel: "บันทึกคำตอบฉบับร่าง",
    evaluateLabel: "ประเมินตามเกณฑ์",
    retryLabel: "เริ่มแก้ไขคำตอบรอบถัดไป",
    saved: "บันทึกคำตอบบนเซิร์ฟเวอร์แล้ว",
    conflict: "มีการแก้ไขใหม่กว่า โปรดโหลดหน้าอีกครั้งก่อนดำเนินการต่อ",
    failed: "ดำเนินการไม่สำเร็จ โปรดลองใหม่โดยไม่ส่งซ้ำอย่างรวดเร็ว",
    incomplete: "เลือกคำตอบให้ครบทั้งสามข้อก่อนประเมิน",
    met: "ผ่านเกณฑ์",
    notMet: "ยังไม่ผ่านเกณฑ์",
    feedbackHeading: "ผลตามเกณฑ์ที่บันทึกไว้",
    demonstratedHeading: "แสดงพฤติกรรมตามเกณฑ์ครบแล้ว",
    retryHeading: "ยังต้องปรับคำตอบและลองใหม่",
    noXp: "ผลนี้ไม่บันทึก XP และไม่ใช่ผลรับรองทักษะ",
    revisionTemplate: "ฉบับแก้ไข {revision}",
    backLabel: "กลับหน้าความคืบหน้า",
  },
  en: {
    metadataTitle: "Persisted source-verification practice | Rise Pals",
    metadataDescription:
      "A synthetic practice space with server-persisted responses and rubric results.",
    learningEyebrow: "Synthetic learning area",
    learningHeading: "Learning progress",
    learningIntroduction:
      "This page shows only example activity saved under the current account and consent grant.",
    lessonLink: "Open the persisted lesson and practice",
    notStarted: "Not started",
    inProgress: "Practice in progress",
    needsRetry: "Revise and try again",
    demonstrated: "All criteria demonstrated",
    boundaryHeading: "Synthetic-alpha boundary",
    boundaries: [
      "Selected option IDs and progress are stored for the signed-in account; email is not copied into learning records.",
      "No free text or file is collected, and proof submission remains unavailable.",
      "This is not evidence that the lesson is effective or validated with real users.",
      "No XP, proof submission or personalized recommendation is saved.",
      "Viewing a page performs no write; progress changes only through explicit actions.",
    ],
    consentHeading: "Current service-data consent is required",
    consentBody: "Open onboarding to review and grant the current consent before saving progress.",
    signInHeading: "Sign in required",
    unavailableHeading: "The learning area is unavailable",
    startLabel: "Start and save progress",
    saveLabel: "Save draft response",
    evaluateLabel: "Evaluate against the rubric",
    retryLabel: "Start the next revision",
    saved: "The response was saved on the server.",
    conflict: "A newer revision exists. Reload before continuing.",
    failed: "The action failed. Try again without rapidly resubmitting.",
    incomplete: "Select an answer for all three criteria before evaluation.",
    met: "Criterion met",
    notMet: "Criterion not met",
    feedbackHeading: "Saved criterion result",
    demonstratedHeading: "All criteria demonstrated",
    retryHeading: "Revise the response and try again",
    noXp: "This result saves no XP and is not a validated skill outcome.",
    revisionTemplate: "Revision {revision}",
    backLabel: "Back to learning progress",
  },
} as const satisfies Record<Locale, Readonly<Record<string, string | readonly string[]>>>;

export type PersistedLessonCopy = (typeof persistedLessonCopy)[Locale];
