import type { Locale } from "@/lib/i18n/config";

export const persistedLessonCopy = {
  th: {
    metadataTitle: "ฝึกตรวจสอบแหล่งข้อมูลแบบบันทึกความคืบหน้า | Rise Pals",
    metadataDescription: "พื้นที่ฝึกสังเคราะห์ที่บันทึกคำตอบและผลตามเกณฑ์บนเซิร์ฟเวอร์",
    learningEyebrow: "การฝึกของคุณ",
    learningHeading: "ฝึกไปถึงไหนแล้ว?",
    learningIntroduction: "ดูความคืบหน้าที่บันทึกไว้ในบัญชีทดลองของคุณ",
    lessonLink: "ฝึกแล้วบันทึกผล",
    notStarted: "ยังไม่ได้เริ่ม",
    inProgress: "กำลังฝึก",
    needsRetry: "ลองปรับคำตอบอีกครั้ง",
    demonstrated: "ผ่านครบทุกข้อแล้ว",
    boundaryHeading: "การบันทึกข้อมูล",
    boundaries: [
      "บันทึกตัวเลือกและความคืบหน้าในบัญชี ไม่คัดลอกอีเมลมาเก็บในผลการฝึก",
      "ยังพิมพ์ข้อความ อัปโหลด หรือส่งผลงานไม่ได้",
      "เดโมนี้ยังไม่ผ่านการทดสอบผลการเรียนรู้กับผู้ใช้จริง",
      "ยังไม่สะสม XP หรือแนะนำการฝึกเฉพาะคุณ",
      "การเปิดหน้าไม่บันทึกข้อมูล ต้องกดเริ่มหรือบันทึกก่อน",
    ],
    consentHeading: "ยินยอมใช้ข้อมูลก่อนบันทึก",
    consentBody: "ไปอ่านรายละเอียดและเลือกยินยอมในหน้าตั้งค่า",
    signInHeading: "ต้องลงชื่อเข้าใช้",
    unavailableHeading: "ยังเปิดพื้นที่เรียนรู้ไม่ได้",
    startLabel: "เริ่มฝึกและบันทึก",
    saveLabel: "บันทึกคำตอบฉบับร่าง",
    evaluateLabel: "ดูผลการฝึก",
    retryLabel: "แก้คำตอบอีกครั้ง",
    saved: "บันทึกคำตอบบนเซิร์ฟเวอร์แล้ว",
    conflict: "มีคำตอบใหม่กว่า ลองโหลดหน้าใหม่ก่อนนะ",
    failed: "ยังทำรายการไม่ได้ ลองใหม่อีกครั้งนะ",
    incomplete: "เลือกคำตอบให้ครบทั้งสามข้อก่อนประเมิน",
    met: "ผ่านเกณฑ์",
    notMet: "ยังไม่ผ่านเกณฑ์",
    feedbackHeading: "ผลตามเกณฑ์ที่บันทึกไว้",
    demonstratedHeading: "ผ่านครบทุกข้อแล้ว",
    retryHeading: "ยังต้องปรับคำตอบและลองใหม่",
    noXp: "ผลนี้ไม่บันทึก XP และไม่ใช่ผลรับรองทักษะ",
    revisionTemplate: "ฉบับแก้ไข {revision}",
    backLabel: "กลับหน้าความคืบหน้า",
  },
  en: {
    metadataTitle: "Persisted source-verification practice | Rise Pals",
    metadataDescription:
      "A synthetic practice space with server-persisted responses and rubric results.",
    learningEyebrow: "YOUR PRACTICE",
    learningHeading: "Your progress",
    learningIntroduction: "Practice saved to your test account.",
    lessonLink: "Practise and save",
    notStarted: "Not started",
    inProgress: "Practice in progress",
    needsRetry: "Revise and try again",
    demonstrated: "All criteria demonstrated",
    boundaryHeading: "About saved progress",
    boundaries: [
      "Your choices and progress are saved to your account, without copying your email.",
      "No text entry, uploads or proof submission yet.",
      "Learning outcomes have not been validated with real users.",
      "No XP or personalised recommendations yet.",
      "Opening this page saves nothing. Use Start or Save to record progress.",
    ],
    consentHeading: "Review data consent first",
    consentBody: "Open setup to review and allow data use before saving.",
    signInHeading: "Sign in required",
    unavailableHeading: "The learning area is unavailable",
    startLabel: "Start and save progress",
    saveLabel: "Save draft response",
    evaluateLabel: "See how you did",
    retryLabel: "Revise your answers",
    saved: "The response was saved on the server.",
    conflict: "A newer revision exists. Reload before continuing.",
    failed: "The action failed. Try again without rapidly resubmitting.",
    incomplete: "Select an answer for all three criteria before evaluation.",
    met: "Criterion met",
    notMet: "Criterion not met",
    feedbackHeading: "Saved criterion result",
    demonstratedHeading: "All criteria demonstrated",
    retryHeading: "Revise the response and try again",
    noXp: "This result saves no XP and is not a validated skill outcome.",
    revisionTemplate: "Revision {revision}",
    backLabel: "Back to learning progress",
  },
} as const satisfies Record<Locale, Readonly<Record<string, string | readonly string[]>>>;

export type PersistedLessonCopy = (typeof persistedLessonCopy)[Locale];
